allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: false
packages:
  - 'plugins/*'
