'use client'
import {def} from "@/plugins/client/api";

import * as module0 from '@/business/client/navigation';
import * as module1 from '@/engines/lorebooks/client/match';
import * as module2 from '@/llmapis/client/input-builder';
import * as module3 from '@/llmapis/client/config';
import * as module4 from '@/llmapis/client/tabs';
import * as module5 from '@/presets/client/tabs';
import * as module6 from '@/slots/client/conversation';
import * as module7 from '@/slots/client/feature';
import * as module8 from '@/stories/client/tabs';
import * as module9 from '@/components/template/navigation-template';
import * as module10 from '@/components/template/content-template';
import * as module11 from '@/components/template/edit-form-template';
import * as module12 from '@/components/template/entry-list-template';
import * as module13 from '@/components/ui/accordion';
import * as module14 from '@/components/ui/alert-dialog';
import * as module15 from '@/components/ui/button';
import * as module16 from '@/components/ui/button-group';
import * as module17 from '@/components/ui/card';
import * as module18 from '@/components/ui/checkbox';
import * as module19 from '@/components/ui/collapsible';
import * as module20 from '@/components/ui/combobox';
import * as module21 from '@/components/ui/dialog';
import * as module22 from '@/components/ui/empty';
import * as module23 from '@/components/ui/field';
import * as module24 from '@/components/ui/input';
import * as module25 from '@/components/ui/input-group';
import * as module26 from '@/components/ui/item';
import * as module27 from '@/components/ui/label';
import * as module28 from '@/components/ui/navigation-menu';
import * as module29 from '@/components/ui/pagination';
import * as module30 from '@/components/ui/resizable';
import * as module31 from '@/components/ui/select';
import * as module32 from '@/components/ui/separator';
import * as module33 from '@/components/ui/skeleton';
import * as module34 from '@/components/ui/sonner';
import * as module35 from '@/components/ui/switch';
import * as module36 from '@/components/ui/tabs';
import * as module37 from '@/components/ui/textarea';
import * as module38 from '@/components/ui/tooltip';
import * as module39 from '@/components/ui/dropdown-menu';
import * as module40 from 'react';
import * as module41 from 'react/jsx-runtime';
import * as module42 from 'react/jsx-dev-runtime';
import * as module43 from 'next-intl';
import * as module44 from '@monaco-editor/react';
import * as module45 from 'monaco-editor';

export const buildPluginApi = () => {
    def('@/business/client/navigation', module0);
    def('@/engines/lorebooks/client/match', module1);
    def('@/llmapis/client/input-builder', module2);
    def('@/llmapis/client/config', module3);
    def('@/llmapis/client/tabs', module4);
    def('@/presets/client/tabs', module5);
    def('@/slots/client/conversation', module6);
    def('@/slots/client/feature', module7);
    def('@/stories/client/tabs', module8);
    def('@/components/template/navigation-template', module9);
    def('@/components/template/content-template', module10);
    def('@/components/template/edit-form-template', module11);
    def('@/components/template/entry-list-template', module12);
    def('@/components/ui/accordion', module13);
    def('@/components/ui/alert-dialog', module14);
    def('@/components/ui/button', module15);
    def('@/components/ui/button-group', module16);
    def('@/components/ui/card', module17);
    def('@/components/ui/checkbox', module18);
    def('@/components/ui/collapsible', module19);
    def('@/components/ui/combobox', module20);
    def('@/components/ui/dialog', module21);
    def('@/components/ui/empty', module22);
    def('@/components/ui/field', module23);
    def('@/components/ui/input', module24);
    def('@/components/ui/input-group', module25);
    def('@/components/ui/item', module26);
    def('@/components/ui/label', module27);
    def('@/components/ui/navigation-menu', module28);
    def('@/components/ui/pagination', module29);
    def('@/components/ui/resizable', module30);
    def('@/components/ui/select', module31);
    def('@/components/ui/separator', module32);
    def('@/components/ui/skeleton', module33);
    def('@/components/ui/sonner', module34);
    def('@/components/ui/switch', module35);
    def('@/components/ui/tabs', module36);
    def('@/components/ui/textarea', module37);
    def('@/components/ui/tooltip', module38);
    def('@/components/ui/dropdown-menu', module39);
    def('react', module40);
    def('react/jsx-runtime', module41);
    def('react/jsx-dev-runtime', module42);
    def('next-intl', module43);
    def('@monaco-editor/react', module44);
    def('monaco-editor', module45);
};
