/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/llmapis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-llmapis"];
        put?: never;
        /** 创建预设 */
        post: operations["post-llmapis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-llmapis-{id}"];
        /** 更新预设 */
        put: operations["put-llmapis-{id}"];
        post?: never;
        /** 删除预设 */
        delete: operations["delete-llmapis-{id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 调用指定 LLM API 进行流式对话 */
        post: operations["post-llmapis-{id}-chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-llmapis-{id}-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}/entries/{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取条目分页列表 */
        get: operations["get-llmapis-{id}-entries-{entryType}"];
        put?: never;
        /** 创建条目 */
        post: operations["post-llmapis-{id}-entries-{entryType}"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}/entries/{entryType}/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-llmapis-{id}-entries-{entryType}-{entryId}"];
        post?: never;
        /** 删除条目 */
        delete: operations["delete-llmapis-{id}-entries-{entryType}-{entryId}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llmapis/{id}/entries/{entryType}/{entryId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-llmapis-{id}-entries-{entryType}-{entryId}-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-plugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/{pluginId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get-plugins-{pluginId}"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-presets"];
        put?: never;
        /** 创建预设 */
        post: operations["post-presets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-presets-{id}"];
        /** 更新预设 */
        put: operations["put-presets-{id}"];
        post?: never;
        /** 删除预设 */
        delete: operations["delete-presets-{id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-presets-{id}-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取条目分页列表 */
        get: operations["get-presets-{id}-entries-{entryType}"];
        put?: never;
        /** 创建条目 */
        post: operations["post-presets-{id}-entries-{entryType}"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-presets-{id}-entries-{entryType}-{entryId}"];
        post?: never;
        /** 删除条目 */
        delete: operations["delete-presets-{id}-entries-{entryType}-{entryId}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}/{entryId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-presets-{id}-entries-{entryType}-{entryId}-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-stories"];
        put?: never;
        /** 创建预设 */
        post: operations["post-stories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-stories-{id}"];
        /** 更新预设 */
        put: operations["put-stories-{id}"];
        post?: never;
        /** 删除预设 */
        delete: operations["delete-stories-{id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-stories-{id}-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取故事及其依赖的所有预设（含详情） */
        get: operations["get-stories-{id}-slot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取条目分页列表 */
        get: operations["get-stories-{id}-entries-{entryType}"];
        put?: never;
        /** 创建条目 */
        post: operations["post-stories-{id}-entries-{entryType}"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-stories-{id}-entries-{entryType}-{entryId}"];
        post?: never;
        /** 删除条目 */
        delete: operations["delete-stories-{id}-entries-{entryType}-{entryId}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}/{entryId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-stories-{id}-entries-{entryType}-{entryId}-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        any: unknown;
        BaseModel: {
            id: string;
            name: string;
            entries?: {
                [key: string]: unknown;
            };
            content: {
                [key: string]: unknown;
            };
        };
        EntryModel: {
            id: number;
            /** @description 编码，同预设下唯一 */
            disabled: boolean;
            /** @description 名称 */
            code: string;
            /** @description 名称 */
            name: string;
        };
        LlmapiModel: {
            id?: string;
            name?: string;
            entries?: {
                [key: string]: unknown;
            };
            content?: {
                [key: string]: unknown;
            };
            code: string;
            /** @description 模型供应者 */
            version: string;
            /** @description api key secret */
            provider?: string;
            /** @description api key secret */
            key?: string;
            builder?: string;
        };
        LlmInputModel: unknown;
        PagedResult: {
            data: unknown[];
            totalCount: number;
        };
        "PagedResult<any>": {
            data: unknown[];
            totalCount: number;
        };
        "PagedResult<LlmapiModel>": {
            data: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                code: string;
                /** @description 模型供应者 */
                version: string;
                /** @description api key secret */
                provider?: string;
                /** @description api key secret */
                key?: string;
                builder?: string;
            }[];
            totalCount: number;
        };
        "PagedResult<PresetModel>": {
            data: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                code: string;
                version: string;
                tags: string[];
                requires: {
                    code: string;
                    version: string;
                }[];
            }[];
            totalCount: number;
        };
        "PagedResult<StoryModel>": {
            data: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                requires: {
                    code: string;
                    version: string;
                }[];
                llmapi: {
                    code: string;
                    version: string;
                } | null;
                histories?: {
                    id?: number;
                    /** @description 编码，同预设下唯一 */
                    disabled?: boolean;
                    /** @description 名称 */
                    code?: string;
                    /** @description 名称 */
                    name?: string;
                    outputId: number;
                    summary: boolean;
                    variables: {
                        [key: string]: unknown;
                    };
                    inputs: {
                        content?: string;
                        variables?: {
                            op: string;
                            path: string;
                            value: unknown;
                        }[];
                        properties?: {
                            [key: string]: unknown;
                        };
                        id: number;
                    }[];
                    outputs: {
                        content?: string;
                        variables?: {
                            op: string;
                            path: string;
                            value: unknown;
                        }[];
                        properties?: {
                            [key: string]: unknown;
                        };
                        id: number;
                    }[];
                }[];
            }[];
            totalCount: number;
        };
        PageOptions: {
            /** @description 页码，默认0 */
            page?: number;
            /** @description 每页条数，默认20 */
            pageSize?: number;
            /** @description 可选搜索项 */
            search?: unknown;
        };
        PluginManifest: {
            id?: string;
            requires?: string[];
            /** @description 后端脚本名称 */
            version: string;
            /** @description 前端脚本名称 */
            serverScript?: string;
            /** @description 前端脚本名称 */
            clientScript?: string;
            /** @description 目录, 加载后赋值, 默认空字符串 */
            path: string;
            /** @description 目录, 加载后赋值, 默认空字符串 */
            directory?: string;
        };
        PresetModel: {
            id?: string;
            name?: string;
            entries?: {
                [key: string]: unknown;
            };
            content?: {
                [key: string]: unknown;
            };
            code: string;
            version: string;
            tags: string[];
            requires: {
                code: string;
                version: string;
            }[];
        };
        ReadableStream: unknown;
        Registerable: {
            id: string;
            requires?: string[];
        };
        RequireModel: {
            code: string;
            version: string;
        };
        SlotModel: {
            id?: string;
            name?: string;
            entries?: {
                [key: string]: unknown;
            };
            content?: {
                [key: string]: unknown;
            };
            story: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                requires: {
                    code: string;
                    version: string;
                }[];
                llmapi: {
                    code: string;
                    version: string;
                } | null;
                histories?: {
                    id?: number;
                    /** @description 编码，同预设下唯一 */
                    disabled?: boolean;
                    /** @description 名称 */
                    code?: string;
                    /** @description 名称 */
                    name?: string;
                    outputId: number;
                    summary: boolean;
                    variables: {
                        [key: string]: unknown;
                    };
                    inputs: {
                        content?: string;
                        variables?: {
                            op: string;
                            path: string;
                            value: unknown;
                        }[];
                        properties?: {
                            [key: string]: unknown;
                        };
                        id: number;
                    }[];
                    outputs: {
                        content?: string;
                        variables?: {
                            op: string;
                            path: string;
                            value: unknown;
                        }[];
                        properties?: {
                            [key: string]: unknown;
                        };
                        id: number;
                    }[];
                }[];
            };
            presets: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                code: string;
                version: string;
                tags: string[];
                requires: {
                    code: string;
                    version: string;
                }[];
            }[];
            llmapi: {
                id?: string;
                name?: string;
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                code: string;
                /** @description 模型供应者 */
                version: string;
                /** @description api key secret */
                provider?: string;
                /** @description api key secret */
                key?: string;
                builder?: string;
            };
        };
        StoryHistory: {
            id?: number;
            /** @description 编码，同预设下唯一 */
            disabled?: boolean;
            /** @description 名称 */
            code?: string;
            /** @description 名称 */
            name?: string;
            outputId: number;
            summary: boolean;
            variables: {
                [key: string]: unknown;
            };
            inputs: {
                content?: string;
                variables?: {
                    op: string;
                    path: string;
                    value: unknown;
                }[];
                properties?: {
                    [key: string]: unknown;
                };
                id: number;
            }[];
            outputs: {
                content?: string;
                variables?: {
                    op: string;
                    path: string;
                    value: unknown;
                }[];
                properties?: {
                    [key: string]: unknown;
                };
                id: number;
            }[];
        };
        StoryHistoryMessage: {
            content: string;
            variables: {
                op: string;
                path: string;
                value: unknown;
            }[];
            properties: {
                [key: string]: unknown;
            };
        };
        StoryInputMessage: {
            content?: string;
            variables?: {
                op: string;
                path: string;
                value: unknown;
            }[];
            properties?: {
                [key: string]: unknown;
            };
            id: number;
        };
        StoryModel: {
            id?: string;
            name?: string;
            entries?: {
                [key: string]: unknown;
            };
            content?: {
                [key: string]: unknown;
            };
            requires: {
                code: string;
                version: string;
            }[];
            llmapi: {
                code: string;
                version: string;
            } | null;
            histories?: {
                id?: number;
                /** @description 编码，同预设下唯一 */
                disabled?: boolean;
                /** @description 名称 */
                code?: string;
                /** @description 名称 */
                name?: string;
                outputId: number;
                summary: boolean;
                variables: {
                    [key: string]: unknown;
                };
                inputs: {
                    content?: string;
                    variables?: {
                        op: string;
                        path: string;
                        value: unknown;
                    }[];
                    properties?: {
                        [key: string]: unknown;
                    };
                    id: number;
                }[];
                outputs: {
                    content?: string;
                    variables?: {
                        op: string;
                        path: string;
                        value: unknown;
                    }[];
                    properties?: {
                        [key: string]: unknown;
                    };
                    id: number;
                }[];
            }[];
        };
        StoryOutputMessage: {
            content?: string;
            variables?: {
                op: string;
                path: string;
                value: unknown;
            }[];
            properties?: {
                [key: string]: unknown;
            };
            id: number;
        };
        VariableChangeModel: {
            op: string;
            path: string;
            value: unknown;
        };
    };
    responses: {
        /** @description Bad Request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Invalid request parameters */
                    error?: string;
                    /** @example 400 */
                    code?: string;
                };
            };
        };
        /** @description Unauthorized */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Authentication required */
                    error?: string;
                    /** @example 401 */
                    code?: string;
                };
            };
        };
        /** @description Forbidden */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Access denied */
                    error?: string;
                    /** @example 403 */
                    code?: string;
                };
            };
        };
        /** @description Not Found */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Resource not found */
                    error?: string;
                    /** @example 404 */
                    code?: string;
                };
            };
        };
        /** @description Conflict */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Resource already exists */
                    error?: string;
                    /** @example 409 */
                    code?: string;
                };
            };
        };
        /** @description Internal Server Error */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example An unexpected errors occurred */
                    error?: string;
                    /** @example 500 */
                    code?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-llmapis": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<LlmapiModel>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-llmapis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LlmapiModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-llmapis-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmapiModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-llmapis-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-llmapis-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-llmapis-{id}-chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LlmInputModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-llmapis-{id}-export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadableStream"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-llmapis-{id}-entries-{entryType}": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<any>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-llmapis-{id}-entries-{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-llmapis-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-llmapis-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-llmapis-{id}-entries-{entryType}-{entryId}-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginManifest"][];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-plugins-{pluginId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: pluginId
                 * @example 123
                 */
                pluginId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<PresetModel>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PresetModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}-export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadableStream"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}-entries-{entryType}": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<any>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-presets-{id}-entries-{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-presets-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}-entries-{entryType}-{entryId}-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<StoryModel>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoryModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}-export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadableStream"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}-slot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}-entries-{entryType}": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<any>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-stories-{id}-entries-{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-stories-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}-entries-{entryType}-{entryId}-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
}
