import {def} from "@/plugins/client/api";

import * as module0 from '@/business/client/navigation';
import * as module1 from '@/business/client/template/tab-header';
import * as module2 from '@/business/client/template';
import * as module3 from '@/engines/lorebooks/client/match';
import * as module4 from '@/llmapis/client/input-builder';
import * as module5 from '@/llmapis/client/config';
import * as module6 from '@/llmapis/client/tabs';
import * as module7 from '@/presets/client/tabs';
import * as module8 from '@/slots/client/conversation';
import * as module9 from '@/slots/client/feature';
import * as module10 from '@/stories/client/tabs';
import * as module11 from '@/components/custom/accessible';
import * as module12 from '@/components/custom/image-uploader';
import * as module13 from '@/components/custom/combobox';
import * as module14 from '@/components/custom/pager';
import * as module15 from '@/components/custom/tab';
import * as module16 from '@/components/ui/accordion';
import * as module17 from '@/components/ui/alert-dialog';
import * as module18 from '@/components/ui/aspect-ratio';
import * as module19 from '@/components/ui/button';
import * as module20 from '@/components/ui/button-group';
import * as module21 from '@/components/ui/card';
import * as module22 from '@/components/ui/checkbox';
import * as module23 from '@/components/ui/collapsible';
import * as module24 from '@/components/ui/combobox';
import * as module25 from '@/components/ui/dialog';
import * as module26 from '@/components/ui/empty';
import * as module27 from '@/components/ui/field';
import * as module28 from '@/components/ui/input';
import * as module29 from '@/components/ui/input-group';
import * as module30 from '@/components/ui/item';
import * as module31 from '@/components/ui/label';
import * as module32 from '@/components/ui/navigation-menu';
import * as module33 from '@/components/ui/pagination';
import * as module34 from '@/components/ui/resizable';
import * as module35 from '@/components/ui/select';
import * as module36 from '@/components/ui/separator';
import * as module37 from '@/components/ui/skeleton';
import * as module38 from '@/components/ui/sonner';
import * as module39 from '@/components/ui/switch';
import * as module40 from '@/components/ui/tabs';
import * as module41 from '@/components/ui/textarea';
import * as module42 from '@/components/ui/tooltip';
import * as module43 from '@/components/ui/dropdown-menu';
import * as module44 from 'react';
import * as module45 from 'react/jsx-runtime';
import * as module46 from 'react/jsx-dev-runtime';
import * as module47 from 'next-intl';
import * as module48 from '@monaco-editor/react';
import * as module49 from 'monaco-editor';

export const buildPluginApi = () => {
    def('@/business/client/navigation', module0);
    def('@/business/client/template/tab-header', module1);
    def('@/business/client/template', module2);
    def('@/engines/lorebooks/client/match', module3);
    def('@/llmapis/client/input-builder', module4);
    def('@/llmapis/client/config', module5);
    def('@/llmapis/client/tabs', module6);
    def('@/presets/client/tabs', module7);
    def('@/slots/client/conversation', module8);
    def('@/slots/client/feature', module9);
    def('@/stories/client/tabs', module10);
    def('@/components/custom/accessible', module11);
    def('@/components/custom/image-uploader', module12);
    def('@/components/custom/combobox', module13);
    def('@/components/custom/pager', module14);
    def('@/components/custom/tab', module15);
    def('@/components/ui/accordion', module16);
    def('@/components/ui/alert-dialog', module17);
    def('@/components/ui/aspect-ratio', module18);
    def('@/components/ui/button', module19);
    def('@/components/ui/button-group', module20);
    def('@/components/ui/card', module21);
    def('@/components/ui/checkbox', module22);
    def('@/components/ui/collapsible', module23);
    def('@/components/ui/combobox', module24);
    def('@/components/ui/dialog', module25);
    def('@/components/ui/empty', module26);
    def('@/components/ui/field', module27);
    def('@/components/ui/input', module28);
    def('@/components/ui/input-group', module29);
    def('@/components/ui/item', module30);
    def('@/components/ui/label', module31);
    def('@/components/ui/navigation-menu', module32);
    def('@/components/ui/pagination', module33);
    def('@/components/ui/resizable', module34);
    def('@/components/ui/select', module35);
    def('@/components/ui/separator', module36);
    def('@/components/ui/skeleton', module37);
    def('@/components/ui/sonner', module38);
    def('@/components/ui/switch', module39);
    def('@/components/ui/tabs', module40);
    def('@/components/ui/textarea', module41);
    def('@/components/ui/tooltip', module42);
    def('@/components/ui/dropdown-menu', module43);
    def('react', module44);
    def('react/jsx-runtime', module45);
    def('react/jsx-dev-runtime', module46);
    def('next-intl', module47);
    def('@monaco-editor/react', module48);
    def('monaco-editor', module49);
};
