/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-presets"];
        put?: never;
        /** 创建预设 */
        post: operations["post-presets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-presets-{id}"];
        /** 更新预设 */
        put: operations["put-presets-{id}"];
        post?: never;
        /** 删除预设 */
        delete: operations["delete-presets-{id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-presets-{id}-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取条目分页列表 */
        get: operations["get-presets-{id}-entries-{entryType}"];
        put?: never;
        /** 创建条目 */
        post: operations["post-presets-{id}-entries-{entryType}"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-presets-{id}-entries-{entryType}-{entryId}"];
        post?: never;
        /** 删除条目 */
        delete: operations["delete-presets-{id}-entries-{entryType}-{entryId}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{id}/entries/{entryType}/{entryId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-presets-{id}-entries-{entryType}-{entryId}-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设分页列表 */
        get: operations["get-stories"];
        put?: never;
        /** 创建预设 */
        post: operations["post-stories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-stories-{id}"];
        /** 更新预设 */
        put: operations["put-stories-{id}"];
        post?: never;
        /** 删除预设 */
        delete: operations["delete-stories-{id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取预设 */
        get: operations["get-stories-{id}-export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取条目分页列表 */
        get: operations["get-stories-{id}-entries-{entryType}"];
        put?: never;
        /** 创建条目 */
        post: operations["post-stories-{id}-entries-{entryType}"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-stories-{id}-entries-{entryType}-{entryId}"];
        post?: never;
        /** 删除条目 */
        delete: operations["delete-stories-{id}-entries-{entryType}-{entryId}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}/entries/{entryType}/{entryId}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新条目 */
        put: operations["put-stories-{id}-entries-{entryType}-{entryId}-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        any: unknown;
        BaseModel: {
            id: string;
            name: string;
            requires: {
                code: string;
                version: string;
            }[];
            entries?: {
                [key: string]: unknown;
            };
            content: {
                [key: string]: unknown;
            };
        };
        PagedResult: {
            data: unknown[];
            totalCount: number;
        };
        "PagedResult<any>": {
            data: unknown[];
            totalCount: number;
        };
        "PagedResult<PresetModel>": {
            data: {
                id?: string;
                name?: string;
                requires?: {
                    code: string;
                    version: string;
                }[];
                entries?: {
                    [key: string]: unknown;
                };
                content?: {
                    [key: string]: unknown;
                };
                code: string;
                version: string;
                tags: string[];
            }[];
            totalCount: number;
        };
        "PagedResult<StoryModel>": {
            data: {
                id: string;
                name: string;
                requires: {
                    code: string;
                    version: string;
                }[];
                entries?: {
                    [key: string]: unknown;
                };
                content: {
                    [key: string]: unknown;
                };
            }[];
            totalCount: number;
        };
        PageOptions: {
            /** @description 页码，默认0 */
            page?: number;
            /** @description 每页条数，默认20 */
            pageSize?: number;
            /** @description 可选搜索项 */
            search?: unknown;
        };
        PresetModel: {
            id?: string;
            name?: string;
            requires?: {
                code: string;
                version: string;
            }[];
            entries?: {
                [key: string]: unknown;
            };
            content?: {
                [key: string]: unknown;
            };
            code: string;
            version: string;
            tags: string[];
        };
        ReadableStream: unknown;
        RequireModel: {
            code: string;
            version: string;
        };
        StoryModel: {
            id: string;
            name: string;
            requires: {
                code: string;
                version: string;
            }[];
            entries?: {
                [key: string]: unknown;
            };
            content: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad Request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Invalid request parameters */
                    error?: string;
                    /** @example 400 */
                    code?: string;
                };
            };
        };
        /** @description Unauthorized */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Authentication required */
                    error?: string;
                    /** @example 401 */
                    code?: string;
                };
            };
        };
        /** @description Forbidden */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Access denied */
                    error?: string;
                    /** @example 403 */
                    code?: string;
                };
            };
        };
        /** @description Not Found */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Resource not found */
                    error?: string;
                    /** @example 404 */
                    code?: string;
                };
            };
        };
        /** @description Conflict */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Resource already exists */
                    error?: string;
                    /** @example 409 */
                    code?: string;
                };
            };
        };
        /** @description Internal Server Error */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example An unexpected errors occurred */
                    error?: string;
                    /** @example 500 */
                    code?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-presets": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<PresetModel>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PresetModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-presets-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}-export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadableStream"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-presets-{id}-entries-{entryType}": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<any>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-presets-{id}-entries-{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-presets-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-presets-{id}-entries-{entryType}-{entryId}-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<StoryModel>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StoryModel"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetModel"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-stories-{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}-export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadableStream"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "get-stories-{id}-entries-{entryType}": {
        parameters: {
            query?: {
                /** @description 页码，默认0 */
                page?: number;
                /** @description 每页条数，默认20 */
                pageSize?: number;
                /** @description 可选搜索项 */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResult<any>"];
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "post-stories-{id}-entries-{entryType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["any"];
            };
        };
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "delete-stories-{id}-entries-{entryType}-{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    "put-stories-{id}-entries-{entryType}-{entryId}-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Path parameter: id
                 * @example 123
                 */
                id: number;
                /**
                 * @description Path parameter: entryType
                 * @example example
                 */
                entryType: string;
                /**
                 * @description Path parameter: entryId
                 * @example 123
                 */
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
}
